front_home:
    path:     /
    defaults: { _controller: FrontBundle:Home:index }

login:
    path:     /connexion
    defaults: { _controller: mowlkky.controller.back.login:loginAction }

logout:
    path: /deconnexion

backend:
    prefix:   /gestion
    resource: '@BackBundle/Resources/config/routing.yml'