# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        repository:
            id: mowlkky.security.user_authentication_provider

    encoders:
        Wanimo\Mowlkky\CoreBundle\Security\UserAuthentication: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /connexion
                check_path: /connexion
            logout:
                path:   /deconnexion
                target: /
