Wanimo\Mowlkky\CoreDomain\User\Security:
    type: embeddable
    fields:
        password:
            column: password
            type: string
            nullable: false
            length: 64
        salt:
            column: salt
            type: string
            nullable: false
            length: 64