Wanimo\Mowlkky\CoreDomain\User\Password\EncodedPassword:
    type: embeddable
    fields:
        value:
            column: password
            type: string
            nullable: false
            length: 64
